### PR TITLE
Traduction française de la formation front-end

### PR DESCRIPTION
**Pull request by Abdel-MalikSimplon**
Il reste encore beaucoup à traduire.

### CODE REVIEW

**Comment by olivierlacan** [comment]
Merci Abdel. :-)

**Comment by Vadorequest** [comment]
@olivierlacan Si je reprends le taff fait et que je le termine, ça sera vraiment mergé ? Ce dépôt semble un peu abandonné.

**Comment by snychka** [comment]
@Vadorequest sorry about there being no response!  Olivier is busy with other things.  Although it'll be slow, I will be looking into this.  Can't promise we can get them up, but I'll try.

I'd guess starting in about 2 weeks.  If you're still interested and I haven't heard back, please @ github me in a couple weeks.  Oh, and sorry, I don't speak French.

**Comment by snychka** [comment]
@Vadorequest I have a review scheduled for next week, so will very likely be staring on this then.  I'll keep you apprised of progress made.

**Comment by snychka** [comment]
Just reviewed, so now need to do the merge and deploy.  Likely later this week.  Will ping you when Iv'e done that.

**Comment by snychka** [comment]
d'oh, wish I would've noticed this earlier, but it was only partially translated.  Tough to notice when you're translating a foreign language that was only partially translated; guess it translated english to english, too 😄 

Anyway, have removed the file.  Feel free to open another pull request if you can do at least the entire level!

**Comment by Vadorequest** [comment]
@snychka hi, sorry for the late answer. I actually asked about whether, if I complete the job that had been started it would eventually get merged, since all this seemed a bit left alone. I didn't want to translate it if it's no use to nobody.

**Pull request merged**
