### PR TITLE
Add Russian subtitles for Try SQL (1-2-ru.srt)

### PR DESCRIPTION
**Pull request by feelingit**

### CODE REVIEW

**Comment by snychka** [comment]
@feelingit, thank you, I'm aware, and will check these out _likely_ tomorrow, but will for sure at least make some headway by next week!

**Comment by snychka** [comment]
@feelingit thanks!

A couple things first:

- Instead of including the merge which updated your repo. in the pull request, just include the addition of your 1-2-ru.srt file (I still need to review that, and will when you create a new Pull Request with solely that change)
- make 2 separate pull requests, one for the aforementioned Russian subtitles, and also (and thanks!) one for the Shaping Up fix.

Thanks!

**Comment by feelingit** [comment]
Sorry!

**Comment by snychka** [comment]
Nah, no worries at all!

I _could've_ merged, as there weren't effectively any changes but 1) I wasn't positive 2) it looks messy.

And I think I did this myself a while back when I didn't first pull to update things locally, and my commit included a large useless merge.  For another repo., and the dev was nice and let it slide.

**Pull request closed without merging**
