### PR TITLE
Fix for Russian subtitles for Try SQL (1-3-ru.srt)

### PR DESCRIPTION
**Pull request by feelingit**
I have created a new file. I hope it works.

### CODE REVIEW

**Comment by snychka** [comment]
Hey @feelingit !  Letting you know I'm aware.

But, do note:  based on some testing before, I don't think it's your file.  It's on our end.  So, our fault likely, not yours.

I will try, though, later on, probably tomorrow!

**Comment by feelingit** [comment]
@snychka, I'm not sure, but I think that first file was wrong. That file looked different in my system. I send you my screenshot in the forum.

**Comment by feelingit** [comment]
I don't think that it is your problem. It is the third file already and we had no such problem before.

**Comment by snychka** [comment]
Okay.  I started trying this out, but as before, google translate per page isn't working.  I'll need to use the google translate web page, which is more limited and takes more time.

I'll resume no later than Tuesday, probably on the weekend, and I'll keep you updated with any progress!

**Comment by feelingit** [comment]
@snychka, you can try [Google Translator Toolkit](https://translate.google.com/toolkit/). It's convenient for subtitles and has no limitations: 

screen shot 2018-01-13 at 20 59 37

screen shot 2018-01-13 at 21 02 31

**Comment by snychka** [comment]
<details>
<summary>more dets</summary>

1
00: 00: 02,040 -> 00: 00: 03,220
Welcome
again in Try SQL.

2
00: 00: 03,220 -> 00: 00: 05,080
I hope you get
Pleasure, as I do.

3
00: 00: 05,080 -> 00: 00: 06,540
Let's continue.

4
00: 00: 06,540 -> 00: 00: 10,209
In the third part we will get acquainted
with data criteria.

5
00: 00: 10,209 -> 00: 00: 11,750
In the previous section
we learned how to allocate

6th
00: 00: 11,750 -> 00: 00: 14,590
and filter the data,
which we want to find.

7th
00: 00: 14,590 -> 00: 00: 17,320
But what if we want to sort
this data in a special way?

8
00: 00: 17,320 -> 00: 00: 20,810
For example, if we want
find all movie titles

9
00: 00: 20,810 -> 00: 00: 25,140
and sort them by length
or the length of the film?

10
00: 00: 25,140 -> 00: 00: 27,810
To achieve this goal, we
we use a new SQL recipe.

eleven
00: 00: 27,810 -> 00: 00: 29,700
Let's call it the ORDER BY recipe.

12
00: 00: 29,700 -> 00: 00: 30,680
Let's take a look!

13
00: 00: 30,680 -> 00: 00: 34,310
We use the same conditions
SELECT and FROM, as usual,

14
00: 00: 34,310 -> 00: 00: 37,860
but after the condition FROM
add the ORDER BY clause.

15
00: 00: 37,860 -> 00: 00: 40,860
This will allow us to sort
data on columns so,

16
00: 00: 40,860 -> 00: 00: 44,010
as we want to see them.

17th
00: 00: 44,010 -> 00: 00: 45,740
Let's return to our question.

18
00: 00: 45,740 -> 00: 00: 47,520
We want to receive
all movie titles

19
00: 00: 47,520 -> 00: 00: 49,780
and sort them
by duration.

20
00: 00: 49,780 -> 00: 00: 53,490
To begin with, we must
select them from the title column.

21
00: 00: 53,490 -> 00: 00: 55,700
Using
ORDER BY clauses

22
00: 00: 55,700 -> 00: 00: 57,330
we can also choose
way to view data -

23
00: 00: 57,330 -> 00: 01: 00,430
in ascending order
or decrease.

24
00: 01: 00,430 -> 00: 01: 02,150
Therefore, considering,
what are we looking for

25
00: 01: 02,150 -> 00: 01: 05,430
results from the title column,

26th
00: 01: 05,430 -> 00: 01: 07,680
we also need to remember,
that we sort the column

27th
00: 01: 07,680 -> 00: 01: 10,750
title for the smallest
duration.

28
00: 01: 10,750 -> 00: 01: 13,355
This is one of the advantages
ORDER BY clauses.

29
00: 01: 17,690 -> 00: 01: 19,810
Now, if we do
query SELECT, we can

thirty
00: 01: 19,810 -> 00: 01: 22,640
see what movie titles are
return in order

31
00: 01: 22,640 -> 00: 01: 25,110
increase, or from a smaller
duration to greater.

32
00: 01: 25,110 -> 00: 01: 27,610
This means that headings first
sorted by the smallest

33
00: 01: 27,610 -> 00: 01: 30,400
duration, but the title
with the highest duration

34
00: 01: 30,400 -> 00: 01: 33,220
should be the last, because
duration increases

35
00: 01: 33,220 -> 00: 01: 34,970
with an increase in the number of results.

36
00: 01: 34,970 -> 00: 01: 37,880
Please note that we
do not return in results

37
00: 01: 37,880 -> 00: 01: 39,905
duration of films, and
only organized headlines.

38
00: 01: 42,470 -> 00: 01: 44,290
But you can do it differently,

39
00: 01: 44,290 -> 00: 01: 46,850
returning movie titles

40
00: 01: 46,850 -> 00: 01: 48,680
in descending order.

41
00: 01: 48,680 -> 00: 01: 51,280
This means that the first
returns header

42
00: 01: 51,280 -> 00: 01: 54,490
the film with a maximum
duration,

43
00: 01: 54,490 -> 00: 01: 57,790
and the last with the least.

44
00: 01: 57,790 -> 00: 02: 01,540
Please note that DESC
is used to denote,

45
00: 02: 01,540 -> 00: 02: 03,750
when the ORDER BY clause
is performed in this way.

46
00: 02: 03,750 -> 00: 02: 06,900
SQL automatically assumes,
that if DESC is not specified,

47
00: 02: 06,900 -> 00: 02: 09,229
the result will be returned
in ascending order,

48
00: 02: 09,229 -> 00: 02: 12,400
as we saw earlier.

49
00: 02: 12,400 -> 00: 02: 14,040
So, now we have found
several different ways

50
00: 02: 14,040 -> 00: 02: 17,520
improve SQL search, including
some search criteria.

51
00: 02: 17,520 -> 00: 02: 21,100
But what if we want to return
specific data ranges

52
00: 02: 21,100 -> 00: 02: 24,980
based on comparison, including
some boundary value?

53
00: 02: 24,980 -> 00: 02: 28,370
As an example, let's
using SQL we get all

54
00: 02: 28,370 -> 00: 02: 31,799
movies duration
more than 100 minutes.

55
00: 02: 31,799 -> 00: 02: 33,340
We are not looking for films,
with duration

56
00: 02: 33,340 -> 00: 02: 36,840
exactly 100 minutes, but only
those films, the length of which

57
00: 02: 36,840 -> 00: 02: 38,290
more than 100 minutes.

58
00: 02: 38,290 -> 00: 02: 40,590
We will use the recipe
SELECT ... FROM ... WHERE ...

59
00: 02: 40,590 -> 00: 02: 44,220
and include the comparison operator
between two objects.

60
00: 02: 44,220 -> 00: 02: 47,820
Here you can see
comparison operator.

61
00: 02: 47,820 -> 00: 02: 51,210
The sign "more", usually
used in mathematics,

62
00: 02: 51,210 -> 00: 02: 53,740
means that all elements
in this column should be

63
00: 02: 53,740 -> 00: 02: 58,070
greater than the value specified
to the right of the sign.


</details>

**Comment by snychka** [comment]
Hi! it worked!  It may've also been that I tried the deploy on a newer machine.  Not sure.

**Comment by feelingit** [comment]
Wow, I'm so glad! Thank you!

**Pull request merged**
