### PR TITLE
This is my spanish translation for level 1 - Javascript Road Trip 1 (more to come)

### PR DESCRIPTION
**Pull request by carloscarvallo**
This is my [Report Card](https://www.codeschool.com/users/carloscarvallo)

### CODE REVIEW

**Comment by carloscarvallo** [comment]
I think my translation will be quite useful, why don't merge on the repository :disappointed:

**Comment by snychka** [comment]
@carloscarvallo I'm going to leave this one open and see if it's okay.  Sorry for no previous response.

But me if you haven't heard back in a couple week!

**Comment by carloscarvallo** [comment]
How is going with the corrections? @snychka

**Comment by snychka** [comment]
Thanks for the bump, and I apologize  @carloscarvallo as I had missed this (I don't think my email is prioritizing notifications from this repository 😞  )  Will check into this as I'm likely doing another one soon too, so it's likely I'll have this done before the end of the year.  Will keep you apprised!

**Comment by snychka** [comment]
checklist for review:

- [x] [1a](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level1a-es.srt)
- [ ] [1b](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level1b-es.srt)
- [ ] [2a](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level2a-es.srt)
- [ ] [2b](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level2b-es.srt)
- [ ] [3a](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level3a-es.srt)
- [ ] [3b](https://raw.githubusercontent.com/codeschool/subtitles/72ade019600778aa78c94e885d0cff4fa752fb9b/javascript-roadtrip-1/level3b-es.srt)

**Comment by snychka** [comment]
@carloscarvallo got to this a bit later than I wanted.  Sorry about the delay.  I just started looking at this, and it'll take a little while, mainly due to the number of files, and a bit due to the english file that was fixed.  You can see the review-progress  above.  Once that's all done, it'll likely be an easy deploy.  There may be an issue with the english file change, but I doubt it.

I'll github-ping (@) you once they're deployed, or if I have any questions or changes that need to be made!

**Comment by snychka** [comment]
Okay @carloscarvallo your subtitles are up there.  Thanks!

**Pull request merged**
