### PR TITLE
Translates first level of adventures in web animations to brazilian portuguese

### PR DESCRIPTION
**Pull request by ricardovsilva**
It's also serves for other countries that has portuguese as native language. But, as like differences between en-UK and en-US, there are some differences between pt-BR and just pt.
At this point, I already translated level one, and PLEASE, if some other portuguese fluent can review this, I will really appreciate this.

Observation: I chose to not translate opening jingle and some technical terms.

### CODE REVIEW

**Comment by ricardovsilva** [comment]
Already done translation of all levels. Just need review and merge :). TY for all codeschool crew for this awesome course.

**Comment by snychka** [comment]
Thank you @ricardovsilva !  Going to look into this (a couple other colleagues let me know) and we'll see how it goes.  I'll get back to you.  Likely will start on this tomorrow!

**Comment by snychka** [comment]
@ricardovsilva you can check things out at https://www.codeschool.com/courses/adventures-in-web-animations/videos !

**Comment by ricardovsilva** [comment]
Awesome! Any feedbacks? I will try translate other two courses at this weekend.

**Comment by snychka** [comment]
I don't speak Portuguese, so did a quick check only.  Technically, it looks ok, but of course I don't know if it perfectly matches.  Keep in mind I will probably try to do about 1 or 2 per week, so it'll be a bit slow.

Oh, right, next week I'm out on conference, so may be more of a delay.

**Pull request merged**
