### PR TITLE
Adding Brazilian Portuguese for the intro of Rails for Zombies

### PR DESCRIPTION
**Pull request by heitorsilva**
Hope you like it.

Later I'll do more translations

### CODE REVIEW

**Comment by snychka** [comment]
Hey @heitorsilva and thanq!  I'll check into this I hope within about a month, and I'll try for much earlier.

**Comment by snychka** [comment]
@heitorsilva I've put it down on my to-do list for next week, so should be able to start looking into this

**Comment by snychka** [comment]
@heitorsilva just checking into this, and please change the file name to intro-pt.srt

1. We currently have -pt in our list
1. I couldn't easily find if -pt_br adheres to a standard

If you wish, I can check into this more and ask the developer who made this to allow for -pt_br if possible.  We probably can do that, but I can't guarantee.

github @ me when done!

**Comment by heitorsilva** [comment]
@snychka, pt is not pt_br, because pt = Portugal and pt_br = Brazil...

even being both "Portuguese", they're very different, and every i18n system treats them as 'pt' and 'pt_br' (or 'pt-br').

if we leave as just 'pt', no one will know that it's Brazilian Portuguese, and not Portugal Portuguese.

**Comment by snychka** [comment]
I see @heitorsilva thanks for the explanation.  We only currently support the _pt extension.   I'll see if this can be accommodated for and will get back to you!

**Comment by adamfortuna** [comment]
For now we can go with Portuguese, and have that mean Brazilian Portuguese -- since we have far more people in that neck of the woods plying our courses. We'll add it to our internal list to split that out somewhere down the line!

**Comment by snychka** [comment]
Cool!  @heitorsilva please change it over to -pt and @ me when done!

**Comment by heitorsilva** [comment]
@snychka You mean rails-for-zombies/intro-pt-br.srt ?

**Comment by snychka** [comment]
> @snychka You mean rails-for-zombies/intro-pt-br.srt 

Yep!  ➡️  rails-for-zombies/intro-pt.srt

**Comment by heitorsilva** [comment]
Done @snychka!

**Comment by snychka** [comment]
Awesome, @heitorsilva, thank you!  Will merge and deploy maybe today, and if not, then tomorrow.

**Comment by snychka** [comment]
Deployed @heitorsilva !  Sorry about the delay, and thank you very much for doing this.

**Pull request merged**
