### PR TITLE
Add Russian subtitles for Try SQL (1-1-ru.srt)

### PR DESCRIPTION
**Pull request by feelingit**
Russian subtitles for Try SQL (1-1-ru.srt)

### CODE REVIEW

**Comment by snychka** [comment]
Hello, and thanks!  I'll review these later on this week.

**Comment by snychka** [comment]
I reviewed this, and I'll later this week merge and deploy

https://github.com/codeschool/subtitles/pull/40/commits/eaabbdc48d61ceb4191b9955a35177670cab9651

tq!

**Comment by snychka** [comment]
Aaach, really sorry, I complete forgot about this.  I have it on my calendar to do in the next couple days.

**Comment by snychka** [comment]
It's been merged and deployed to production!  Thanq!

**Comment by feelingit** [comment]
Stefan, thank you!

**Pull request merged**
