### PR TITLE
Create 1-2-tr.srt

### PR DESCRIPTION
**Pull request by omergulen**

### CODE REVIEW

**Comment by snychka** [comment]
Hey, thanks for doing this.  Letting you know I'm aware, and will look these over later this week!

**Comment by snychka** [comment]
@omergulen hello!  Please let me know what ulaşabilrisiniz means, and also can you point to a web page where it's used in context.  Thanks!

**Comment by omergulen** [comment]
It means "you can reach" or "you can get"  etc...
[Here Link](http://www.bilgisayardershanesi.com/bilgisayar_dersleri/dreamweaver-ve-metinler.html)

**Comment by snychka** [comment]
@omergulen thq!  merged, and deployed.  Please check'em out--just skimming, so 3 spot-checks, 1 toward the beginning, 1 in the middle, 1 at the end for me--would be great!  You can see the vids at

https://www.codeschool.com/courses/try-python/videos

(may need to refresh first)

**Comment by omergulen** [comment]
- [+] Python Math 

- [+] Using Variables

- [+] Introduction to Strings

- [+] Strings and Slices

- [-] Introduction to Conditionals _will be added_

- [-] More Conditionals _will be added_

checked all and made some corrections

**Pull request merged**
