### PR TITLE
Add Russian subtitles for Git Real (1,2,3,4 - ru.srt)

### PR DESCRIPTION
**Pull request by IgorPolyakov**

### CODE REVIEW

**Comment by snychka** [comment]
@IgorPolyakov , tq, just letting you know I'm aware of this, and will likely start looking at this at some point this week!

**Comment by snychka** [comment]
Sorry @IgorPolyakov .  We had a couple outages on Friday and this weekend, so my time was spent with other things.

I should still be able to get to this, but it may not be til later this week.

**Comment by IgorPolyakov** [comment]
All OK)
I slowly continue to translate `GitReal`.

**Comment by snychka** [comment]
@IgorPolyakov thank you, they've been reviewed, merged, and deployed!

**Pull request merged**
