### PR TITLE
Add Russian subtitles for Try SQL (1-3-ru.srt)

### PR DESCRIPTION
**Pull request by feelingit**

### CODE REVIEW

**Comment by snychka** [comment]
Hi @feelingit !

Sorry for not noticing this earlier.

I'll look into this later this week!

**Comment by snychka** [comment]
Hi!  Sorry for not getting to this when I said.

Looking into it new.  in-Chrome translation isn't working, will have to try a few other things

**Comment by snychka** [comment]
had to use https://translate.google.ca/

<details>
<summary>further details</summary>

- didn't allow more than about 65 sections (5000 characters) at a time

```
1
00: 00: 02,040 -> 00: 00: 03,220
Welcome
again in Try SQL.

2
00: 00: 03,220 -> 00: 00: 05,080
I hope you get
Pleasure, as I do.

3
00: 00: 05,080 -> 00: 00: 06,540
Let's continue.

4
00: 00: 06,540 -> 00: 00: 10,209
In the third part we will get acquainted
with data criteria.

5
00: 00: 10,209 -> 00: 00: 11,750
In the previous section
we learned how to allocate

6th
00: 00: 11,750 -> 00: 00: 14,590
and filter the data,
which we want to find.

7th
00: 00: 14,590 -> 00: 00: 17,320
But what if we want to sort
this data in a special way?

8
00: 00: 17,320 -> 00: 00: 20,810
For example, if we want
find all movie titles

9
00: 00: 20,810 -> 00: 00: 25,140
and sort them by length
or the length of the film?

10
00: 00: 25,140 -> 00: 00: 27,810
To achieve this goal, we
we use a new SQL recipe.

eleven
00: 00: 27,810 -> 00: 00: 29,700
Let's call it the ORDER BY recipe.

12
00: 00: 29,700 -> 00: 00: 30,680
Let's take a look!

13
00: 00: 30,680 -> 00: 00: 34,310
We use the same conditions
SELECT and FROM, as usual,

14
00: 00: 34,310 -> 00: 00: 37,860
but after the condition FROM
add the ORDER BY clause.

15
00: 00: 37,860 -> 00: 00: 40,860
This will allow us to sort
data on columns so,

16
00: 00: 40,860 -> 00: 00: 44,010
as we want to see them.

17th
00: 00: 44,010 -> 00: 00: 45,740
Let's return to our question.

18
00: 00: 45,740 -> 00: 00: 47,520
We want to receive
all movie titles

19
00: 00: 47,520 -> 00: 00: 49,780
and sort them
by duration.

20
00: 00: 49,780 -> 00: 00: 53,490
To begin with, we must
select them from the title column.

21
00: 00: 53,490 -> 00: 00: 55,700
Using
ORDER BY clauses

22
00: 00: 55,700 -> 00: 00: 57,330
we can also choose
way to view data -

23
00: 00: 57,330 -> 00: 01: 00,430
in ascending order
or decrease.

24
00: 01: 00,430 -> 00: 01: 02,150
Therefore, considering,
what are we looking for

25
00: 01: 02,150 -> 00: 01: 05,430
results from the title column,

26th
00: 01: 05,430 -> 00: 01: 07,680
we also need to remember,
that we sort the column

27th
00: 01: 07,680 -> 00: 01: 10,750
title for the smallest
duration.

28
00: 01: 10,750 -> 00: 01: 13,355
This is one of the advantages
ORDER BY clauses.

29
00: 01: 17,690 -> 00: 01: 19,810
Now, if we do
query SELECT, we can

thirty
00: 01: 19,810 -> 00: 01: 22,640
see what movie titles are
return in order

31
00: 01: 22,640 -> 00: 01: 25,110
increase, or from a smaller
duration to greater.

32
00: 01: 25,110 -> 00: 01: 27,610
This means that headings first
sorted by the smallest

33
00: 01: 27,610 -> 00: 01: 30,400
duration, but the title
with the highest duration

34
00: 01: 30,400 -> 00: 01: 33,220
should be the last, because
duration increases

35
00: 01: 33,220 -> 00: 01: 34,970
with an increase in the number of results.

36
00: 01: 34,970 -> 00: 01: 37,880
Please note that we
do not return in results

37
00: 01: 37,880 -> 00: 01: 39,905
duration of films, and
only organized headlines.

38
00: 01: 42,470 -> 00: 01: 44,290
But you can do it differently,

39
00: 01: 44,290 -> 00: 01: 46,850
returning movie titles

40
00: 01: 46,850 -> 00: 01: 48,680
in descending order.

41
00: 01: 48,680 -> 00: 01: 51,280
This means that the first
returns header

42
00: 01: 51,280 -> 00: 01: 54,490
the film with a maximum
duration,

43
00: 01: 54,490 -> 00: 01: 57,790
and the last with the least.

44
00: 01: 57,790 -> 00: 02: 01,540
Please note that DESC
is used to denote,

45
00: 02: 01,540 -> 00: 02: 03,750
when the ORDER BY clause
is performed in this way.

46
00: 02: 03,750 -> 00: 02: 06,900
SQL automatically assumes,
that if DESC is not specified,

47
00: 02: 06,900 -> 00: 02: 09,229
the result will be returned
in ascending order,

48
00: 02: 09,229 -> 00: 02: 12,400
as we saw earlier.

49
00: 02: 12,400 -> 00: 02: 14,040
So, now we have found
several different ways

50
00: 02: 14,040 -> 00: 02: 17,520
improve SQL search, including
some search criteria.

51
00: 02: 17,520 -> 00: 02: 21,100
But what if we want to return
specific data ranges

52
00: 02: 21,100 -> 00: 02: 24,980
based on comparison, including
some boundary value?

53
00: 02: 24,980 -> 00: 02: 28,370
As an example, let's
using SQL we get all

54
00: 02: 28,370 -> 00: 02: 31,799
movies duration
more than 100 minutes.

55
00: 02: 31,799 -> 00: 02: 33,340
We are not looking for films,
with duration

56
00: 02: 33,340 -> 00: 02: 36,840
exactly 100 minutes, but only
those films, the length of which

57
00: 02: 36,840 -> 00: 02: 38,290
more than 100 minutes.

58
00: 02: 38,290 -> 00: 02: 40,590
We will use the recipe
SELECT ... FROM ... WHERE ...

59
00: 02: 40,590 -> 00: 02: 44,220
and include the comparison operator
between two objects.

60
00: 02: 44,220 -> 00: 02: 47,820
Here you can see
comparison operator.

61
00: 02: 47,820 -> 00: 02: 51,210
The sign "more", usually
used in mathematics,

62
00: 02: 51,210 -> 00: 02: 53,740
means that all elements
in this column should be

63
00: 02: 53,740 -> 00: 02: 58,070
greater than the value specified
to the right of the sign.

64
00: 02: 58,070 -> 00: 02: 58,920
But you know what?

65
00: 02: 58,920 -> 00: 03: 01,910
We are already familiar
with a comparison operator.

66
00: 03: 01,910 -> 00: 03: 02,490
Right.

67
00: 03: 02,490 -> 00: 03: 04,860
The "equal" sign is
also the type of comparison.

68
00: 03: 04,860 -> 00: 03: 06,980
This query does not return
records corresponding to

69
00: 03: 06,980 -> 00: 03: 09,610
conditions of comparison,
because there are no movies

70
00: 03: 09,610 -> 00: 03: 15,520
duration
exactly 100 minutes.

71
00: 03: 15,520 -> 00: 03: 19,480
But if we use the sign
"More" in the WHERE clause,

72
00: 03: 19,480 -> 00: 03: 21,530
we get this record.

73
00: 03: 21,530 -> 00: 03: 23,270
Since the "Metropolis"

74
00: 03: 23,270 -> 00: 03: 26,900
this is the only
film in the table,

75
00: 03: 26,900 -> 00: 03: 28,780
appropriate
conditions of the request,

76
00: 03: 28,780 -> 00: 03: 31,200
duration

77
00: 03: 31,200 -> 00: 03: 33,820
more than 100 minutes.

78
00: 03: 33,820 -> 00: 03: 35,410
There are other
comparison operators

79
00: 03: 35,410 -> 00: 03: 38,040
used in SQL, which
we want to show you.

80
00: 03: 38,040 -> 00: 03: 40,660
First, when adding
operator "less",

81
00: 03: 40,660 -> 00: 03: 42,770
request will return all records

82
00: 03: 42,770 -> 00: 03: 46,000
with duration
less than 100 minutes.

83
00: 03: 46,000 -> 00: 03: 49,470
If we change it
to the sign "greater than or equal to"

84
00: 03: 49,470 -> 00: 03: 51,540
request will extract
all entries where

85
00: 03: 51,540 -> 00: 03: 55,310
Duration more
or 94 minutes.

86
00: 03: 55,310 -> 00: 03: 57,460
And, finally,
if we change it

87
00: 03: 57,460 -> 00: 04: 00,320
to the sign "less than or equal to"

88
00: 04: 00,320 -> 00: 04: 02,510
request will extract
all entries where

89
00: 04: 02,510 -> 00: 04: 08,570
duration is less
or is equal to 95 minutes.

90
00: 04: 08,570 -> 00: 04: 10,520
We have the last
comparison operator,

91
00: 04: 10,520 -> 00: 04: 12,990
which looks
strange thing

92
00: 04: 12,990 -> 00: 04: 14,260
"less - more".

93
00: 04: 14,260 -> 00: 04: 15,720
What is it???

94
00: 04: 15,720 -> 00: 04: 18,500
This operator finds
all records that

95
00: 04: 18,500 -> 00: 04: 22,340
do not match
with the specified value.

96
00: 04: 22,340 -> 00: 04: 25,050
This sign is not equal.

97
00: 04: 25,050 -> 00: 04: 27,850
Say, for example, you want
see all the movies,

98
00: 04: 27,850 -> 00: 04: 30,250
except for the genre "horror".

99
00: 04: 30,250 -> 00: 04: 33,180
You can use the sign
"Not equal" to get

100
00: 04: 33,180 -> 00: 04: 37,110
all records that do not have
genre "horror", as shown.

101
00: 04: 37,110 -> 00: 04: 40,030
"Metropolis", "The Kid"
and "The Gold Rush"

102
00: 04: 40,030 -> 00: 04: 43,100
do not have the genre of "horror".

103
00: 04: 43,100 -> 00: 04: 45,460
Further, what would we do,
if we want to find

104
00: 04: 45,460 -> 00: 04: 49,300
data corresponding to
several conditions?

105
00: 04: 49,300 -> 00: 04: 51,110
How would we do this?

106
00: 04: 51,110 -> 00: 04: 53,400
Let's say, for example, that we

107
00: 04: 53,400 -> 00: 04: 57,140
want to get all the records,
where at the same time id is 1,

108
00: 04: 57,140 -> 00: 04: 59,380
and genre is equal to "comedy".

109
00: 04: 59,380 -> 00: 05: 01,410
How we can
Is it done with SQL?

110
00: 05: 01,410 -> 00: 05: 05,070
Introducing the new
operator - AND.

111
00: 05: 05,070 -> 00: 05: 07,900
And a new SQL recipe.

112
00: 05: 07,900 -> 00: 05: 11,380
We can use the conditions
SELECT ... FROM ... WHERE ...

113
00: 05: 11,380 -> 00: 05: 14,010
At the end of the query
the AND operator is added,

114
00: 05: 14,010 -> 00: 05: 16,460
to determine
additional

115
00: 05: 16,460 -> 00: 05: 18,160
a criterion for the search.

116
00: 05: 20,800 -> 00: 05: 22,860
Look again
to the Movies table.

117
00: 05: 22,860 -> 00: 05: 27,460
In SQL, when used
operator AND,

118
00: 05: 27,460 -> 00: 05: 30,110
SQL returns result
only when performing

119
00: 05: 30,110 -> 00: 05: 31,720
all conditions.

120
00: 05: 31,720 -> 00: 05: 36,040
When we try to execute
this SELECT,

121
00: 05: 36,040 -> 00: 05: 38,280
we see that in the table
Movies no entries,

122
00: 05: 38,280 -> 00: 05: 41,800
the relevant
all criteria,

123
00: 05: 41,800 -> 00: 05: 43,500
which we are looking for.

124
00: 05: 43,500 -> 00: 05: 46,950
But if we change the genre
of the film "Metropolis"

125
00: 05: 46,950 -> 00: 05: 51,590
on "comedy" instead of "sci-fi"
then we get the result.

126
00: 05: 51,590 -> 00: 05: 55,910
So, given that
Both the WHERE and AND

127
00: 05: 55,910 -> 00: 06: 00,440
must be implemented,
we see that first

128
00: 06: 00,440 -> 00: 06: 02,760
all data are determined,
where id is 1.

129
00: 06: 02,760 -> 00: 06: 05,420
Then the received data
are examined for coincidence

130
00: 06: 05,420 -> 00: 06: 07,240
with the condition "comedy".

131
00: 06: 07,240 -> 00: 06: 10,500
We see that only
heading "Metropolis"

132
00: 06: 10,500 -> 00: 06: 13,640
meets all
search conditions.

133
00: 06: 16,590 -> 00: 06: 19,230
Let's look at another
way to return data


```

</details>

**Comment by snychka** [comment]
Hello @feelingit !  I deployed this, but it isn't showing up.  Not sure what the issue is.

I'll let you know if this can be fixed.  I have asked for help with this, but it is a lower priority.  I don't think it's anything wrong with your file.  Sorry about this, and if we make any progress, I'll let you know.

I'd recommend holding off on other subtitles if and until you hear back from me.

**Comment by feelingit** [comment]
@snychka, I'm very sorry!!!
It seems like something is wrong with my file. 
I have tried to recreate this file again.
I hope it will help!

**Comment by snychka** [comment]
@feelingit , are you sure, or at least fairly sure?

I actually did some testing before, and it seemed it was an issue on our end.  I couldn't for example push up a -ru subtitle for the video with english contents only. Admittedly, I wasn't 100% certain.

**Pull request merged**
